### ISSUE TITLE
No inference support for unique identifiers

### ISSUE THREAD

**Issue by Pansynchro-Admin** [Wittline/csv-schema-inference#25]
This is a pretty well-done project, but it could be improved by adding an inference rule for unique identifiers (GUID/UUID).

**Comment by Wittline** [comment]
> This is a pretty well-done project, but it could be improved by adding an inference rule for unique identifiers (GUID/UUID).

Checking in some "infer data types" projects they are not doing anything for GUID or UUID I think they are inferring those types as STRING directly.

Any thought or could you please help me with some ideas??

**Comment by Pansynchro-Admin** [comment]
If other projects aren't able to do this, this would give yours a competitive advantage if it can. 😄 

> Any thought or could you please help me with some ideas??

The obvious solution is, when you see a string, attempt to parse it as a GUID and see if it's valid.
