### ISSUE TITLE
Any benchmarks for the large files ?

### ISSUE THREAD

**Issue by PandaWhoCodes** [Wittline/csv-schema-inference#28]
Great project
Was wondering if you could provide some benchmarks in the readme for large files >2,3,5 GB csv's so that the community can work towards making things faster.

**Comment by Wittline** [comment]
> Great project Was wondering if you could provide some benchmarks in the readme for large files >2,3,5 GB csv's so that the community can work towards making things faster.

Hi @PandaWhoCodes , I will,  Let me try to find some organic datasets first, I will back to you later.

**Comment by Wittline** [comment]
> Great project Was wondering if you could provide some benchmarks in the readme for large files >2,3,5 GB csv's so that the community can work towards making things faster.

Hi @PandaWhoCodes benchmarks are too slow, I will be working on a new version of the code ir order to improve computations times and memory usage

**Comment by PandaWhoCodes** [comment]
can you share the current benchmarks ?

**Comment by Wittline** [comment]
> can you share the current benchmarks ?

Please check the readme again, **benchmarks** were added, there is another folder **benchmark** with a jupyter notebook..
